spring:
  datasource:
    url: jdbc:postgresql://postgres-companies:5432/companies_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
