version: '3.9'
services:
  postgres-users:
    image: postgres:15
    container_name: postgres-users
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  postgres-companies:
    image: postgres:15
    container_name: postgres-companies
    environment:
      POSTGRES_DB: companies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

#  config-server:
#    build: ./config-server
#    ports:
#      - "8888:8888"
#    volumes:
#      - ./config-repo:/config
#    environment:
#      - SPRING_PROFILES_ACTIVE=native
#      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server

  user-service:
    build: ./user-service
    depends_on:
      - postgres-users
      - config-server
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-users:5432/users_db

  company-service:
    build: ./company-service
    depends_on:
      - postgres-companies
      - config-server
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-companies:5432/companies_db

networks:
  default:
    name: microservices-network
