spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      enabled: false

#  spring.application.name=gateway
#spring.config.import=configserver:

