spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5434/companies_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  cloud:
#    config:
#      enabled: false
#    loadbalancer:
#      ribbon:
#        enabled: false
#    openfeign:
#      client:
#        config:
#          default:
#            connectTimeout: 5000
#            readTimeout: 5000

#spring.application.name=company-service
#spring.config.import=configserver:
server:
  port: 8081
