
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/users_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
#spring.application.name=user-service
#spring.config.import=configserver:
server:
  port: 8080
